export const PUNK_TYPES = ["Female", "Male", "Zombie", "Ape", "Alien"];
export const ALL_ACCESSORIES = [
  "Beanie",
  "Choker",
  "Pilot Helmet",
  "Tiara",
  "Orange Side",
  "Buck Teeth",
  "Welding Goggles",
  "Pigtails",
  "Pink With Hat",
  "Top Hat",
  "Spots",
  "Rosy Cheeks",
  "Blonde Short",
  "Wild White Hair",
  "Cowboy Hat", // 14
  "Wild Blonde",
  "Straight Hair Blonde",
  "Big Beard",
  "Red Mohawk",
  "Half Shaved",
  "Blonde Bob", // 20
  "Vampire Hair",
  "Clown Hair Green",
  "Straight Hair Dark", //23
  "Straight Hair",
  "Silver Chain",
  "Dark Hair",
  "Purple Hair",
  "Gold Chain",
  "Medical Mask", // 29
  "Tassle Hat",
  "Fedora",
  "Police Cap",
  "Clown Nose",
  "Smile", // 34
  "Cap Forward",
  "Hoodie",
  "Front Beard Dark",
  "Frown",
  "Purple Eye Shadow",
  "Handlebars",
  "Blue Eye Shadow",
  "Green Eye Shadow",
  "Vape",
  "Front Beard",
  "Chinstrap",
  "3D Glasses", //46
  "Luxurious Beard",
  "Mustache",
  "Normal Beard Black",
  "Normal Beard",
  "Eye Mask",
  "Goat", //52
  "Do-rag",
  "Shaved Head",
  "Muttonchops",
  "Peak Spike",
  "Pipe",
  "VR",
  "Cap",
  "Small Shades", // 60
  "Clown Eyes Green",
  "Clown Eyes Blue",
  "Headband",
  "Crazy Hair",
  "Knitted Cap", // 65
  "Mohawk Dark",
  "Mohawk",
  "Mohawk Thin",
  "Frumpy Hair",
  "Wild Hair",
  "Messy Hair",
  "Eye Patch", //72
  "Stringy Hair",
  "Bandana",
  "Classic Shades", // 75
  "Shadow Beard",
  "Regular Shades",
  "Horned Rim Glasses",
  "Big Shades",
  "Nerd Glasses", // 80
  "Black Lipstick",
  "Mole", // 82
  "Purple Lipstick",
  "Hot Lipstick",
  "Cigarette",
  "Earring",
];
